<a href="https://colab.research.google.com/github/Kgs-Mathaba/Pytorch-ZTM/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 00. Pytorch fundamentals

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get as int
scalar.item()

7

In [7]:
vec = torch.tensor([7,7])

In [8]:
vec.ndim

1

In [9]:
vec.shape

torch.Size([2])

In [10]:
# Matrix

mat = torch.tensor([[7,8],
                   [9,10]])

In [11]:
mat

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
mat.ndim

2

In [13]:
mat.shape

torch.Size([2, 2])

In [14]:
mat[0]

tensor([7, 8])

In [15]:
mat.shape

torch.Size([2, 2])

In [16]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                       [2,5,4]]])

In [17]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor.ndim

3

In [20]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

### Random tensor

In [21]:
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.8258, 0.8402, 0.6415],
         [0.6779, 0.8183, 0.5448],
         [0.0398, 0.7856, 0.6356],
         [0.0357, 0.4903, 0.8934]],

        [[0.0947, 0.4823, 0.4042],
         [0.5188, 0.7639, 0.8758],
         [0.3373, 0.3826, 0.6617],
         [0.6396, 0.3992, 0.0074]],

        [[0.2016, 0.0019, 0.9166],
         [0.0189, 0.1706, 0.8516],
         [0.2220, 0.6549, 0.1143],
         [0.5564, 0.4333, 0.7412]]])

In [22]:
random_tensor.ndim

3

In [23]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor

tensor([[[0.3193, 0.8670, 0.0993],
         [0.0101, 0.3772, 0.1774],
         [0.9299, 0.1655, 0.2481],
         ...,
         [0.4866, 0.8178, 0.2049],
         [0.2481, 0.6268, 0.1341],
         [0.1518, 0.1357, 0.5313]],

        [[0.4059, 0.8996, 0.4965],
         [0.4708, 0.6366, 0.1665],
         [0.1294, 0.6569, 0.2960],
         ...,
         [0.3450, 0.3519, 0.0121],
         [0.2967, 0.3446, 0.9102],
         [0.5660, 0.6766, 0.2492]],

        [[0.6456, 0.9445, 0.4625],
         [0.3668, 0.5988, 0.1923],
         [0.9014, 0.2868, 0.0954],
         ...,
         [0.7618, 0.6306, 0.0398],
         [0.9436, 0.9511, 0.2451],
         [0.4349, 0.9687, 0.2185]],

        ...,

        [[0.9204, 0.8229, 0.7165],
         [0.5005, 0.7674, 0.9329],
         [0.9755, 0.1250, 0.7165],
         ...,
         [0.6356, 0.7621, 0.9387],
         [0.2709, 0.9675, 0.9759],
         [0.4780, 0.8851, 0.7478]],

        [[0.9581, 0.1111, 0.5131],
         [0.5814, 0.7567, 0.5772],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
torch.randn(2,2,2)

tensor([[[-1.2990, -0.4908],
         [-0.4781,  1.2583]],

        [[ 0.4499,  1.9201],
         [ 0.9132,  1.0989]]])

In [26]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size = (3,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### create range of tensors

In [29]:
torch.range(0,10)

<ipython-input-29-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.__version__

'1.13.0+cu116'

In [31]:
one_to_ten = torch.arange(1, 11, 0.5)


In [32]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
# Float tensor
float_tensor = torch.tensor([3.0, 6.0, 0.9],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor.dtype

torch.float32

In [34]:
float16_tensor = float_tensor.type(torch.float16)

In [35]:
float16_tensor.dtype

torch.float16

In [36]:
t3 = float_tensor * float16_tensor 

In [37]:
t3.dtype

torch.float32

In [38]:
t4 = torch.tensor([3, 6, 9], dtype = torch.int32)
t4.dtype

torch.int32

In [39]:
t5 = float16_tensor*t4
t5.dtype

torch.float16

In [40]:
t6 = torch.tensor([3, 6, 9], dtype = torch.long)
t6.dtype

torch.int64

In [41]:
t7 = torch.rand(3,4)
t7

tensor([[0.3890, 0.3050, 0.9473, 0.2831],
        [0.6545, 0.4081, 0.1073, 0.8222],
        [0.8691, 0.9994, 0.5871, 0.5067]])

In [42]:
t7.dtype

torch.float32

In [43]:
t7.shape

torch.Size([3, 4])

In [44]:
t7.device

device(type='cpu')

In [45]:
tensor1 = torch.tensor([1,2,3])

In [46]:
tensor1 + 10 

tensor([11, 12, 13])

In [47]:
tensor1 + 100

tensor([101, 102, 103])

In [48]:
tensor1 * 100

tensor([100, 200, 300])

In [49]:
tensor1 * -3

tensor([-3, -6, -9])

In [50]:
tensor1.mul(10)

tensor([10, 20, 30])

In [51]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [52]:
tensor * tensor

tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [ 4, 25, 16]]])

In [53]:
torch.matmul(tensor, tensor)

tensor([[[15, 27, 27],
         [36, 63, 66],
         [30, 49, 52]]])

In [54]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
x.min()

tensor(1)

In [56]:
x.max()

tensor(91)

In [57]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [58]:
x.dtype     

torch.int64

In [59]:
x.type(torch.float32).mean()

tensor(46.)

In [60]:
torch.sum(x)

tensor(460)

In [61]:
x.sum()

tensor(460)

In [62]:
torch.sum(x)

tensor(460)

In [63]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [64]:
x.argmin()

tensor(0)

In [65]:
x.argmax()

tensor(9)

In [66]:
x[9]

tensor(91)

In [67]:
a = torch.rand(6,6)
a

tensor([[0.2107, 0.6490, 0.8583, 0.8429, 0.5926, 0.0936],
        [0.8394, 0.6966, 0.4653, 0.6803, 0.8455, 0.9169],
        [0.2116, 0.9614, 0.5828, 0.0921, 0.0888, 0.0395],
        [0.5727, 0.0738, 0.7347, 0.0593, 0.5117, 0.2457],
        [0.3144, 0.2085, 0.7729, 0.3376, 0.0913, 0.2866],
        [0.6010, 0.1858, 0.8851, 0.7409, 0.1897, 0.1681]])

In [68]:
a.argmax()

tensor(13)

In [69]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
x_reshaped = x.reshape(1,1,9)
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [71]:
z = x.view(1, 9)

In [72]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
z[:, 0] = 5

In [74]:
x, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [75]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]), torch.Size([9, 4]))

In [76]:
x_stacked.sum()

tensor(196.)

In [77]:
x = torch.zeros(2,1,2,1,3)
x.size()

torch.Size([2, 1, 2, 1, 3])

In [78]:
torch.unsqueeze(x, dim = 4).size()

torch.Size([2, 1, 2, 1, 1, 3])

In [79]:
x = torch.rand(size=(224,224,3))
x_perm = x.permute(2,0,1)
x_perm.shape

torch.Size([3, 224, 224])

In [80]:
x = torch.arange(1, 10).reshape(1,3,3)

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
x[0][2][0]

tensor(7)

In [86]:
import numpy as np


In [92]:
a = np.arange(1., 8.)
t = torch.from_numpy(a)
a, t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
a.dtype

dtype('float64')

In [96]:
a =a +1

In [97]:
a, t

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [98]:
t = torch.ones(7)
n = t.numpy()
n, t

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [99]:
t = t+1
n, t

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [100]:
a = torch.rand(3,4)
b = torch.rand(3,4)
a == b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [101]:
seed = 42
torch.manual_seed(seed)
c = torch.rand(3,4)
d = torch.rand(3,4)
c, d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [102]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [103]:
torch.cuda.is_available()

False