<a href="https://colab.research.google.com/github/Kgs-Mathaba/Pytorch-ZTM/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## 00. Pytorch fundamentals

In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get as int
scalar.item()

7

In [ ]:
vec = torch.tensor([7,7])

In [ ]:
vec.ndim

1

In [ ]:
vec.shape

torch.Size([2])

In [ ]:
# Matrix

mat = torch.tensor([[7,8],
                   [9,10]])

In [ ]:
mat

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
mat.ndim

2

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
mat[0]

tensor([7, 8])

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                       [2,5,4]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

### Random tensor

In [ ]:
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.1728, 0.1391, 0.7914],
         [0.0994, 0.1748, 0.3766],
         [0.6897, 0.3151, 0.8698],
         [0.9428, 0.2862, 0.3617]],

        [[0.3300, 0.2302, 0.7518],
         [0.3824, 0.2188, 0.6355],
         [0.8218, 0.4010, 0.5808],
         [0.3355, 0.7239, 0.9818]],

        [[0.2397, 0.4861, 0.7000],
         [0.9376, 0.8008, 0.8724],
         [0.4581, 0.6708, 0.2940],
         [0.1394, 0.2263, 0.6555]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor

tensor([[[0.2742, 0.4969, 0.5567],
         [0.9886, 0.7962, 0.5668],
         [0.5407, 0.2825, 0.5500],
         ...,
         [0.4076, 0.4031, 0.8873],
         [0.0846, 0.3095, 0.0133],
         [0.0944, 0.2612, 0.6468]],

        [[0.6971, 0.3063, 0.7011],
         [0.8298, 0.9984, 0.0612],
         [0.7566, 0.4205, 0.2030],
         ...,
         [0.9601, 0.2858, 0.6487],
         [0.1688, 0.5810, 0.4988],
         [0.0783, 0.7035, 0.5408]],

        [[0.2681, 0.6135, 0.6228],
         [0.3718, 0.2137, 0.6860],
         [0.6790, 0.0748, 0.3432],
         ...,
         [0.4962, 0.7219, 0.1270],
         [0.6627, 0.2081, 0.4316],
         [0.3416, 0.3313, 0.4658]],

        ...,

        [[0.1820, 0.4797, 0.8262],
         [0.8962, 0.4748, 0.7501],
         [0.1027, 0.5919, 0.3128],
         ...,
         [0.9822, 0.2702, 0.8736],
         [0.6513, 0.9951, 0.3546],
         [0.2769, 0.7123, 0.2855]],

        [[0.9999, 0.3364, 0.3897],
         [0.5051, 0.3492, 0.6102],
         [0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
torch.randn(2,2,2)

tensor([[[-0.8555,  0.5074],
         [-1.1027,  0.9567]],

        [[-0.7102, -1.8066],
         [-1.6359,  1.3531]]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### create range of tensors

In [ ]:
torch.range(0,10)

<ipython-input-29-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.__version__

'1.13.0+cu116'

In [ ]:
one_to_ten = torch.arange(1, 11, 0.5)


In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Float tensor
float_tensor = torch.tensor([3.0, 6.0, 0.9],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float_tensor.type(torch.float16)

In [ ]:
float16_tensor.dtype

torch.float16

In [ ]:
t3 = float_tensor * float16_tensor 

In [ ]:
t3.dtype

torch.float32

In [ ]:
t4 = torch.tensor([3, 6, 9], dtype = torch.int32)
t4.dtype

torch.int32

In [ ]:
t5 = float16_tensor*t4
t5.dtype

torch.float16

In [ ]:
t6 = torch.tensor([3, 6, 9], dtype = torch.long)
t6.dtype

torch.int64

In [ ]:
t7 = torch.rand(3,4)
t7

tensor([[0.3369, 0.6868, 0.2922, 0.5853],
        [0.0370, 0.3380, 0.5242, 0.1482],
        [0.6963, 0.3458, 0.2301, 0.6133]])

In [ ]:
t7.dtype

torch.float32

In [ ]:
t7.shape

torch.Size([3, 4])

In [ ]:
t7.device

device(type='cpu')

In [ ]:
tensor1 = torch.tensor([1,2,3])

In [ ]:
tensor1 + 10 

tensor([11, 12, 13])

In [ ]:
tensor1 + 100

tensor([101, 102, 103])

In [ ]:
tensor1 * 100

tensor([100, 200, 300])

In [ ]:
tensor1 * -3

tensor([-3, -6, -9])

In [ ]:
tensor1.mul(10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [ ]:
tensor * tensor

tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [ 4, 25, 16]]])

In [ ]:
torch.matmul(tensor, tensor)

tensor([[[15, 27, 27],
         [36, 63, 66],
         [30, 49, 52]]])

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.min()

tensor(1)

In [ ]:
x.max()

tensor(91)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
x.dtype     

torch.int64

In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
torch.sum(x)

tensor(460)

In [ ]:
x.sum()

tensor(460)

In [ ]:
torch.sum(x)

tensor(460)

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
a = torch.rand(6,6)
a

tensor([[0.8642, 0.0246, 0.4173, 0.9051, 0.1289, 0.1549],
        [0.0551, 0.0477, 0.6035, 0.3380, 0.1241, 0.5128],
        [0.2596, 0.5100, 0.6592, 0.1227, 0.4128, 0.1611],
        [0.6377, 0.9742, 0.7305, 0.1789, 0.2105, 0.0367],
        [0.8903, 0.2159, 0.0141, 0.5404, 0.0656, 0.9196],
        [0.3534, 0.3487, 0.7352, 0.2282, 0.5408, 0.5854]])

In [ ]:
a.argmax()

tensor(19)

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,1,9)
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
z = x.view(1, 9)

In [ ]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5

In [ ]:
x, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]), torch.Size([9, 4]))

In [ ]:
x_stacked.sum()

tensor(196.)

In [ ]:
x = torch.zeros(2,1,2,1,3)
x.size()

torch.Size([2, 1, 2, 1, 3])

In [ ]:
torch.unsqueeze(x, dim = 4).size()

torch.Size([2, 1, 2, 1, 1, 3])

In [ ]:
x = torch.rand(size=(224,224,3))
x_perm = x.permute(2,0,1)
x_perm.shape

torch.Size([3, 224, 224])

In [ ]:
x = torch.arange(1, 10).reshape(1,3,3)

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][2][0]

tensor(7)

In [ ]:
import numpy as np


In [ ]:
a = np.arange(1., 8.)
t = torch.from_numpy(a)
a, t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a =a +1

In [ ]:
a, t

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
t = torch.ones(7)
n = t.numpy()
n, t

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
t = t+1
n, t

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [ ]:
a = torch.rand(3,4)
b = torch.rand(3,4)
a == b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
seed = 42
torch.manual_seed(seed)
c = torch.rand(3,4)
d = torch.rand(3,4)
c, d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
torch.cuda.is_available()

False

In [ ]:
t = torch.tensor([1,2,3], device = 'cpu')
t.device

device(type='cpu')

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cpu'

In [ ]:
t_gpu = t.to(device)
t_gpu.device

device(type='cpu')